application: hnakamur-vagrant-boxes
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app
  login: admin

- url: /upload
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
